- name: Get stuff from git
  git:
    repo: "https://{{ githubuser | urlencode }}:{{ githubpassword | urlencode }}@github.com/Invideo_task_aws.git"
    dest: /opt
    update: yes
    version: main


- name: build the Docker image
  shell: | 
          cd /opt
          echo "# pull nginx-php image"
          docker pull webdevops/php-nginx:ubuntu-18.04

- name: Run the Docker image
  shell: |
         cd /opt
         echo "# run container with port mapping - host:container"
         docker run -d -p 80:80 --name nginx-php webdevops/php-nginx:ubuntu-18.04
         docker exec -it nginx-php bash -c "echo "<h1>Deployed via Terraform wih ELB</h1>" | sudo tee /var/www/html/index.html"

  






